name: Generate Snake Contribution Graph

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create output directory and a placeholder to ensure the folder exists
      - name: Prepare output directory
        run: |
          mkdir -p dist
          touch dist/.gitkeep   # This ensures the directory is not empty

      # Generate the Snake (SVG + GIF)
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: cutusajda
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Deploy to the output branch
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
          allow_empty_commit: false
          commit_message: "Update snake contribution graph"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
